### ISSUE TITLE
March Meeting Planning

### ISSUE THREAD

**Issue by scmorrison** [aws-ug-yokohama-english/meetings#1]
Hi @jeffusan, @atw-yamamoto

Jeff's idea of using Issues to coordinate the planning is a great idea. Unless we really need a hangout it will be much easier to handle the planning here for everyone.

For this month I wanted to continue with the web architecture workshop. I will walk through the deployment of each of the components manually and explain how they work together. Then, assuming that I can get most of the pieces covered this month, next month will be the last part of the workshop focusing on using CloudFormation to handle the provisioning.

I still haven't updated the agenda, but I will spend some time on it tonight. Also, I am looking at moving to a better presentation format for us. Committing these odt files to our repo is a little too much.

Sam

**Comment by jeffusan** [comment]
This sounds great.

A couple of comments:

1- I got the impression that the majority of the attendees last time were still trying to get a picture of "how can I deploy a website/blog on AWS". If this can be "brought together", or reviewed again, I think that would help several of the attendees.

2- I've been using asciidoctor on a project that is [published on github](http://ktoso.github.io/scala-types-of-types/). I've found it easy to use and enough of a step up over markdown to make it worth while.

**Comment by scmorrison** [comment]
Thanks Jeff,

Yeah, good point. I will spend more time on the basics of each component as I walk through the steps of creating each of the resources.

Thanks for the asciidoctor / asciidoc for the presentations. 

Sam

**Comment by scmorrison** [comment]
Hi @atw-yamamoto, 

What is your topic for this month? I need to add it to the agenda.

Thanks,
Sam

**Comment by toyosge** [comment]
@scmorrison 
I'm so sorry sam. I can't join meetup on this time....
I have many task...

**Comment by scmorrison** [comment]
Hi Massan,

Jeff isn't going to make it either, what should we do? Can we still use the conference room?

Thanks,
Sam

**Comment by scmorrison** [comment]
Hi Jeff, Massan,

Do you know if there are still snacks / drinks? Or do I need to bring some?

Thanks,
Sam

**Comment by jeffusan** [comment]
We still have drinks and snacks! We can come up with an arrangement
tonight.
